name: Install dependencies
description: Install system packages needed for Asimi CLI builds
runs:
  using: composite
  steps:
    - name: Install apt packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgpgme-dev btrfs-progs libbtrfs-dev
